config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls",namespace='homepage')),
    path('auth/',include('account.urls',namespace="account")),
    path('payment/',include('payments.urls',namespace="payments"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from os import name
from django.urls import path
from .views import (index,
mainpage,
about,
courses,
lesson,get_involved,
get_uninvolved,
CourseDetailView,
LessonDetailView,
courses_class_filter,
upload_class,
upload_class_category,
upload_courses,
single_lesson,
lesson_upload_ff,
lesson_file_upload,
upload_assingment_file,
student_enrolled_parent,
courses_recommeondations,
rattings

)

app_name = "homepage"

urlpatterns = [
    path('', index,name="homepage"),
    path('dashbord',mainpage,name='dashboard'),
    path('about/',about,name="about"),
    path('courses/',courses,name="courses"),
    path('single_lesson/',lesson,name="lesson"),
    path('get_involved/',get_involved,name="get_involved"),
    path('get_uninvolved',get_uninvolved,name="get_uninvolved"),
    path('single_course/<slug>/',CourseDetailView.as_view(),name="single_course"),
    path('single_lesson/<slug>/',single_lesson,name="single_lesson"),
    path('course_class_filter/<slug>/',courses_class_filter,name="course_class_filter"),
    path('upload_class/',upload_class,name="upload_class"),
    path("class_category_upload/",upload_class_category, name="class_category_upload"),
    path('upload_courses/',upload_courses,name="upload_courses"),
    path('upload_lesson/',lesson_upload_ff,name="upload_lessons"),
    path('upload_lesson_file/',lesson_file_upload,name="upload_lessons_file"),
    path('upload_assingment_file/',upload_assingment_file,name="upload_assingment_file"),
    path('student_enrolled_parent/',student_enrolled_parent,name="student_enrolled_parent"),
    path('courses_recommendations/',courses_recommeondations,name="courses_recommendations"),
    path('rattings/',rattings,name="rattings")

]

homepage/models.py
from django.db import models
import os
import random
from account.models import User

from courses.models import Lessons


# Create your models here.


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "thumbnails/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class ScrollingIMages(models.Model):
    heading =  models.CharField(max_length=255)
    image = models.ImageField(upload_to = upload_image_path)

    def __str__(self):
        return self.heading


class AboutUs(models.Model):
    heading = models.CharField(max_length=255)
    body =  models.TextField()
    image =  models.ImageField(upload_to=upload_image_path)

    def __str__(self):
        return self.heading

homepage/views.py
from django.core.validators import slug_re
from django.shortcuts import redirect, render
from account.models import User
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect
import uuid
from sklearn.neighbors import NearestNeighbors
from django.http import Http404

from .models import (ScrollingIMages,
AboutUs)
from account.models import Profile_pic
from courses.models import (ClassCategory, Courses,Enrolment,
Classes,
Lessons,
LessonFiles,
LessonAssignmentFiles,
Ratting
)
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView,View,ListView

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.http import HttpResponse
from account.models import ChildEmail


# machine learning recommendation
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        user_obj =  User.objects.get(id= user_id)
        images =  ScrollingIMages.objects.all()
        about =  AboutUs.objects.all()
        all_courses = Courses.objects.all()
        all_enrolment =  Enrolment.objects.filter(user_id = user_obj)
        print(all_enrolment)
        profile_pic =  Profile_pic.objects.all()

        context ={
            'image' :  images,
            'about' : about,
            'all_courses' :  all_courses,
            'all_enrollmet' : all_enrolment,
            'profile_pic' : profile_pic

        }
        return render(request,'index.html',context)

    else:
        images =  ScrollingIMages.objects.all()
        about =  AboutUs.objects.all()
        all_courses = Courses.objects.all()
        


        context ={
            'image' :  images,
            'about' : about,
            'all_courses' :  all_courses,
            

        }
        return render(request,'index.html',context)


def mainpage(request):
    return render(request,'mainpage.html',{})


def about(request):
    all_teachers =  User.objects.all()
    context = {
        'all_teachers' : all_teachers
    }
    return render(request,'about_us.html',context)


def courses(request):
    if request.user.is_authenticated:
        user =  request.user.id
        # get user with the id
        obj = User.objects.get(id=user)
        dict_user =  model_to_dict(obj)
        user_type = dict_user['type']
        courses =  Courses.objects.all()
        all_users =  User.objects.all()
        all_enrolment =  Enrolment.objects.filter(user_id = obj)
        all_classes =  Classes.objects.all()

        context = {
            'user_type' : user_type,
            'courses' :  courses,
            'all_users' :  all_users,
            'all_enrollmet' :  all_enrolment,
            'all_classes' :  all_classes
            
        }

        return render(request,'courses.html',context)

    
    else:
        courses =  Courses.objects.all()
        all_classes =  Classes.objects.all()
      
        all_users =  User.objects.all()
        all_classes =  Classes.objects.all()
        context = {
            'courses' :  courses,
            'all_classes' :  all_classes
            
        }

        return render(request,'courses.html',context)

    
        
        


def lesson(request):
    return render(request,'single_lesson.html')


def single_course(request):
    return render(request,'single_course.html')


def get_involved(request):
    if request.method == "POST":
        course_id = request.POST.get("course_id")
        get_course =  Courses.objects.get(id=course_id)
        user_id = request.user.id
        get_user  =  User.objects.get(id=user_id)
        obj,created =  Enrolment.objects.get_or_create(courses_id = get_course,user_id=get_user)
        obj.enrolled =  True
        obj.save()


        return redirect("homepage:courses")



def get_uninvolved(request):
    if request.method == "POST":
        course_id = request.POST.get("course_id")
        get_course =  Courses.objects.get(id=course_id)
        user_id = request.user.id
        get_user  =  User.objects.get(id=user_id)
        obj=  Enrolment.objects.get(courses_id = get_course,user_id=get_user)
        obj.delete()
      


        return redirect("homepage:courses")


class CourseDetailView(DetailView):
    model = Courses
    template_name = "single_course.html"
    def get_context_data(self, **kwargs):
       
        all_enrolment =  Enrolment.objects.all()
        all_lessons =  Lessons.objects.all()

        context = super().get_context_data(**kwargs)
        context['all_enrollement'] = all_enrolment
        context['all_lessons'] =  all_lessons
        
        
        return context






def single_lesson(request,slug):
    singe_l = Lessons.objects.get(id =  slug)
    all_lessons = Lessons.objects.all()
    all_lesson_files = LessonFiles.objects.all()
    assigments =  LessonAssignmentFiles.objects.all()

    context = {
        'object':singe_l,
        'all_lessons' :  all_lessons,
        'lesson_files' :  all_lesson_files,
        'assignemt_files' :  assigments

    }

    return render(request,'single_lesson.html',context)



class LessonDetailView(DetailView):
    model = Lessons
    template_name = "single_lesson.html"

    def get_context_data(self, **kwargs):
        all_lessons = Lessons.objects.all()
        all_lesson_files = LessonFiles.objects.all()
        assigments =  LessonAssignmentFiles.objects.all()
        context = super().get_context_data(**kwargs)
        context['all_lessons'] =  all_lessons
        context['lesson_files'] =  all_lesson_files
        context['assignemt_files'] =  assigments


def courses_class_filter(request, slug):
    if request.user.is_authenticated:
        user =  request.user.id
        # get user with the id
        obj = User.objects.get(id=user)
        dict_user =  model_to_dict(obj)
        user_type = dict_user['type']
        courses =  Courses.objects.all()
        all_users =  User.objects.all()
        all_enrolment =  Enrolment.objects.all()
        print(slug)
        filtered_classes =  Classes.objects.get(id= slug)
        all_classes =  Classes.objects.all()

        context = {
            'user_type' : user_type,
            'courses' :  courses,
            'all_users' :  all_users,
            'all_enrollmet' :  all_enrolment,
            'all_classes' :  all_classes,
            'filtered_classes' :  filtered_classes
            
        }

        return render(request,'classes_filter.html',context)

    
    else:
        courses =  Courses.objects.all()
        all_classes =  Classes.objects.all()
        filtered_classes =  Classes.objects.get(slug= slug)

        context = {
            
            'courses' :  courses,
            'all_classes' :  all_classes,
            'filtered_classes ' :  filtered_classes
            
        }

        return render(request,'classes_filter.html',context)


def upload_class(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name =  request.POST.get('class_name')
            user =  request.user.id
            # get user with the id
            obju = User.objects.get(id=user)
            slug =  str(uuid.uuid4().hex) + str(class_name).strip().replace(" ","_")
            obj,created = Classes.objects.get_or_create(user_id = obju,slug = slug)
            obj.class_name = class_name
            obj.active =  True
            obj.save()
            request.session['class_id'] = obj.id
            return redirect("homepage:class_category_upload")
    return render(request,'upload_class.html')



def upload_class_category(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name =  request.POST.get('class_title')
            class_uploaded =  request.session['class_id']
            get_class =  Classes.objects.get(id= int(class_uploaded))
            slug =  str(uuid.uuid4().hex) + str(class_name).strip().replace(" ","_")
            obj,created = ClassCategory.objects.get_or_create(class_id = get_class,slug=slug)
            obj.class_title = class_name
            obj.save()
            request.session['class_category_id'] = obj.id
            return redirect("homepage:upload_courses")
    return render(request,'upload_class_category.html')


def upload_courses(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            class_name_title = request.POST.get('course_title')
            class_short_description = request.POST.get('course_short_description')
            class_long_description = request.POST.get('course_long_description')
            class_language = request.POST.get('course_language')
            class_thumbnails = request.FILES['course_thumbnail']
            class_video_url = request.POST.get('video_url')
            user_id =  request.user.id
            user_obj =  User.objects.get(id=  user_id)
            class_category =  request.session['class_category_id']
            slug =  str(uuid.uuid4().hex) + str(class_name_title).strip().replace(" ","_")
            class_category_obj = ClassCategory.objects.get(id =  class_category)
            couses =  Courses.objects.create(
                title = class_name_title,
                teacher_id = user_obj,
                course_category = class_category_obj,
                short_description = class_short_description,
                description = class_long_description,
                language = class_language,
                thumbnail = class_thumbnails,
                video_url = class_video_url,

homepage/templates/course_single/first_single.html
{% load static %}
  <div class="ed_graysection ed_course_single ed_toppadder80 ed_bottompadder80">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="ed_course_single_item">
                            <div class="ed_course_single_image">

                            <iframe width="560" height="315" src="{{object.video_url}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                               
                            </div>
                            <div class="ed_course_single_info">
                                <h2>{{object.title}}</h2>
                                
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                        <div class="course_detail">
                                            <div class="course_faculty">
                                                <img src="{% static 'assets/images/kidscamp/content/team_1.jpg' %}" alt=""> <a href="javascript:void(0);">{{object.teacher_id.username}}</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-12 col-12 pull-right text-right">
                                        <div class="ed_course_duration">
                                            time duration: 75 days

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="ed_course_single_tab">
                                <div role="tabpanel">
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li role="presentation"><a class="active" href="#description" aria-controls="description" role="tab" data-bs-toggle="tab"> short description</a></li>
                                        <li role="presentation"><a href="#students" aria-controls="students" role="tab" data-bs-toggle="tab">students</a></li>
                                        <li role="presentation"><a href="#news" aria-controls="news" role="tab" data-bs-toggle="tab">Full Description</a></li>
                                        <li role="presentation"><a href="#events" aria-controls="events" role="tab" data-bs-toggle="tab">Language</a></li>
                                        <li role="presentation"><a href="#rate" aria-controls="rate" role="tab" data-bs-toggle="tab">Rate</a></li>
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane active" id="description">
                                            <div class="ed_course_tabconetent">
                                                <h2>about course</h2>
                                                <p style="color:black;">{{object.short_description}}</p>

                    
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="students">
                                            <div class="ed_inner_dashboard_info">
                                                <div class="ed_course_single_info">
                                                    <h2>student enrolled :- <span></span></h2>
                                                  
                                                  {% if all_enrollement %}
                                                  {% for als in all_enrollement  %}
                                                  {% if als.courses_id.id ==  object.id %}
                                                    <div class="ed_add_students">
                                                        <img src="{% static 'assets/images/kidscamp/content/S01.jpg' %}" alt="">
                                                        <span>{{als.user_id.username}}</span>
                                                        <p>new student</p>
                                                    </div>
                                                    {% endif %}
                                                    {% endfor %}

                                                {% else %}
                                                <h1> No Student Enrolled Yet </h1>
                                                {% endif %}
                                                
                                                    
                                                    
                                                    
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                                                        <div class="row">
                                                            <div class="ed_blog_bottom_pagination ed_toppadder40">
                                                                <nav>
                                                                    <ul class="pagination">
                                                                        <li><a href="javascript:void(0);">1</a></li>
                                                                        <li><a href="javascript:void(0);">2</a></li>
                                                                        <li><a href="javascript:void(0);">3</a></li>
                                                                        <li class="active"><a href="javascript:void(0);">Next <span class="sr-only">(current)</span></a></li>
                                                                    </ul>
                                                                </nav>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="news">
                                            <div class="ed_course_tabconetent">
                                                <h2>course Full Description</h2>
                                                
                                                <p style="color:black;">{{object.description}}</p>
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="events">
                                            <div class="ed_course_single_info">
                                                <h2>Course Language</h2>
                                                <p style="color:black;">{{object.language}}</p>
                                                
                                                <!--tab End-->
                                            </div>
                                        </div>


                                        <div role="tabpanel" class="tab-pane" id="rate">
                                            <div class="ed_course_single_info">
                                                <h2>Rate Course</h2>
                                                <form method="POST" action="{% url 'homepage:rattings' %}">
                                                    {% csrf_token %}
                                                    <input name="course_id" type="hidden" value="{{object.id}}">
                                                    <select name="ratting" class="form-select" aria-label="Default select example">
                                                        
                                                        <option value="1">1</option>
                                                        <option value="2">2</option>
                                                        <option value="3">3</option>
                                                        <option value="4">4</option>
                                                        <option value="5">5</option>
                                                      </select>

                                                      <button type="submit" class="btn btn-success">Submit</button>
                                                </form>
                                                <!--tab End-->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--tab End-->
                        </div>
                        <div class="ed_time_executor ed_toppadder40">
                            <ul>
                                <li><a href="#">lessons</a> <span>estimated time</span></li>
                                {% if all_lessons %}
                                {% for mk in all_lessons  %}
                                {% if mk.course.id == object.id %}
                                <li><a href="{{mk.get_absolute_url}}">{{mk.title}}</a> <span>{{mk.duration}} Minuts</span></li>

                                {% endif %}
                                {% endfor %}
                               
                                {% endif %}
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>